default: &default
  adapter: postgresql
  pool: 5
  encoding: UTF8
  timeout: 5000

development:
  <<: *default
  username: postgres
  password: root
  database: lawyer_services_dev

test:
  <<: *default
  username: postgres
  password: root  
  database: lawyer_services_test

production:
  <<: *default
  username: postgres
  password: root  
  database: lawyer_services